//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Noside.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Noside.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;name&quot;:&quot;Dollar&quot;,&quot;value&quot;:1,&quot;perRoll&quot;:25},{&quot;name&quot;:&quot;Quarter&quot;,&quot;value&quot;:0.25,&quot;perRoll&quot;:40},{&quot;name&quot;:&quot;Dime&quot;,&quot;value&quot;:0.1,&quot;perRoll&quot;:50},{&quot;name&quot;:&quot;Nickel&quot;,&quot;value&quot;:0.05,&quot;perRoll&quot;:40},{&quot;name&quot;:&quot;Penny&quot;,&quot;value&quot;:0.01,&quot;perRoll&quot;:50}].
        /// </summary>
        internal static string Coins {
            get {
                return ResourceManager.GetString("Coins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count Mismatch.
        /// </summary>
        internal static string CoinViewModel_AddCoins_Count_Mismatch {
            get {
                return ResourceManager.GetString("CoinViewModel_AddCoins_Count_Mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Roll {0}&apos;s{1}Not Enough Coins To Roll.
        /// </summary>
        internal static string CoinViewModel_Roll_Cannot_Roll__0__s_1_Not_Enough_Coins_To_Roll {
            get {
                return ResourceManager.GetString("CoinViewModel_Roll_Cannot_Roll__0__s_1_Not_Enough_Coins_To_Roll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Generic_Error {
            get {
                return ResourceManager.GetString("Generic_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coin Counts.
        /// </summary>
        internal static string Sheet_Name {
            get {
                return ResourceManager.GetString("Sheet_Name", resourceCulture);
            }
        }
    }
}
