//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Noside.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Noside.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Rolls.
        /// </summary>
        public static string CoinCounter_CashRolls_CashRolls {
            get {
                return ResourceManager.GetString("CoinCounter_CashRolls_CashRolls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Rolls.
        /// </summary>
        public static string CoinCounter_MainView_CashRolls {
            get {
                return ResourceManager.GetString("CoinCounter_MainView_CashRolls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolled Value :.
        /// </summary>
        public static string CoinCounter_MainView_RolledValue {
            get {
                return ResourceManager.GetString("CoinCounter_MainView_RolledValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Value :.
        /// </summary>
        public static string CoinCounter_MainView_TotalValue {
            get {
                return ResourceManager.GetString("CoinCounter_MainView_TotalValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrolled Value :.
        /// </summary>
        public static string CoinCounter_MainView_UnrolledValue {
            get {
                return ResourceManager.GetString("CoinCounter_MainView_UnrolledValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;name&quot;:&quot;Dollar&quot;,&quot;value&quot;:1,&quot;perRoll&quot;:25},{&quot;name&quot;:&quot;Quarter&quot;,&quot;value&quot;:0.25,&quot;perRoll&quot;:40},{&quot;name&quot;:&quot;Dime&quot;,&quot;value&quot;:0.1,&quot;perRoll&quot;:50},{&quot;name&quot;:&quot;Nickel&quot;,&quot;value&quot;:0.05,&quot;perRoll&quot;:40},{&quot;name&quot;:&quot;Penny&quot;,&quot;value&quot;:0.01,&quot;perRoll&quot;:50}].
        /// </summary>
        public static string Coins {
            get {
                return ResourceManager.GetString("Coins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count Mismatch.
        /// </summary>
        public static string CoinViewModel_AddCoins_Count_Mismatch {
            get {
                return ResourceManager.GetString("CoinViewModel_AddCoins_Count_Mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Roll {0}&apos;s{1}Not Enough Coins To Roll.
        /// </summary>
        public static string CoinViewModel_NotEnoughCoins {
            get {
                return ResourceManager.GetString("CoinViewModel_NotEnoughCoins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Generic_Add {
            get {
                return ResourceManager.GetString("Generic_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Generic_Error {
            get {
                return ResourceManager.GetString("Generic_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Generic_Reset {
            get {
                return ResourceManager.GetString("Generic_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roll.
        /// </summary>
        public static string Generic_Roll {
            get {
                return ResourceManager.GetString("Generic_Roll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Generic_Save {
            get {
                return ResourceManager.GetString("Generic_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coin Counts.
        /// </summary>
        public static string Sheet_Name {
            get {
                return ResourceManager.GetString("Sheet_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Wyvern {
            get {
                object obj = ResourceManager.GetObject("Wyvern", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Results?.
        /// </summary>
        public static string Wyvern_MainWindow_OnClosing_Save_Results_ {
            get {
                return ResourceManager.GetString("Wyvern_MainWindow_OnClosing_Save_Results_", resourceCulture);
            }
        }
    }
}
